on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      image:
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ inputs.context }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}