on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      image:
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
      use_latest_release:
        required: false
        type: boolean
        default: false
      cache:
        required: false
        type: boolean
        default: ${{ !startsWith(github.ref, 'refs/tags/') && !inputs.use_latest_release }}
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: target-version
        if: ${{ inputs.use_latest_release }}
        run: |
          version=$(gh -R ${{ github.repository }} release view --json name --jq .name)
          echo "version=${version}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.target-version.outputs.version }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          context: git
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ inputs.context }}
          cache-from: ${{ inputs.cache && 'type=gha' || '' }}
          cache-to: ${{ inputs.cache && 'type=gha,mode=max' || '' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864
        if: ${{ !inputs.registry }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ inputs.image }}
          enable-url-completion: true