on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      image:
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
      use_latest_release:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

env:
  USE_CACHE: ${{ !startsWith(github.ref, 'refs/tags/') && !inputs.use_latest_release }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get target version from latest release
        id: target-version
        if: ${{ inputs.use_latest_release }}
        run: |
          version=$(gh -R ${{ github.repository }} release view --json name --jq .name)
          echo "version=${version}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: "Checkout ${{ steps.target-version.outputs.version }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.target-version.outputs.version }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Add metadata to Docker image
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          context: git
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ inputs.context }}
          cache-from: ${{ env.USE_CACHE == 'true' && 'type=gha' || '' }}
          cache-to: ${{ env.USE_CACHE == 'true' && 'type=gha,mode=max' || '' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Update description on Docker Hub
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864
        if: ${{ !inputs.registry }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ inputs.image }}
          enable-url-completion: true