on:
  workflow_call:
    inputs:
      dockerhub_image:
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
      use_latest_release:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

env:
  USE_CACHE: ${{ !startsWith(github.ref, 'refs/tags/') && !inputs.use_latest_release }}

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Downcase repo name
        run: |
          echo "GHCR_IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Get target version from latest release
        id: target-version
        if: ${{ inputs.use_latest_release }}
        run: |
          version=$(gh -R ${{ github.repository }} release view --json name --jq .name)
          echo "version=${version}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: "Checkout ${{ steps.target-version.outputs.version }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.target-version.outputs.version }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Add metadata to Docker image
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_IMAGE }}
            ${{ inputs.dockerhub_image }}
          context: git
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.context }}
          cache-from: ${{ env.USE_CACHE == 'true' && 'type=gha' || '' }}
          cache-to: ${{ env.USE_CACHE == 'true' && 'type=gha,mode=max' || '' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Update description on Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ inputs.dockerhub_image }}
          enable-url-completion: true
