on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      version:
        type: string
        default: ${{ github.ref_name }}
      path:
        type: string
        required: true
      zip_name:
        type: string
        required: true
      additional_files:
        type: string
        required: false
    secrets:
      WEBSITE_UPDATE_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: checkout

      - name: Extract files from Docker image ${{ inputs.image }}:${{ inputs.version }}
        uses: shrink/actions-docker-extract@a0eaa32fe671598e765702e505fc8446d9984b4e
        with:
          image: ${{ inputs.image }}:${{ inputs.version }}
          path: ${{ inputs.path }}/.
          destination: app

      - name: Copy default files
        run: cd checkout && cp CHANGELOG.md LICENSE README.md ../app

      - name: Copy additional files
        if: ${{ inputs.additional_files }}
        run: cd checkout && cp -r ${{ inputs.additional_files }} ../app

      - name: Create zip file ${{ inputs.zip_name }}-${{ github.ref_name }}.zip
        run: cd app && zip -r ../${{ inputs.zip_name }}-${{ github.ref_name }}.zip .

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: checkout/CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: ${{ inputs.zip_name }}-${{ github.ref_name }}.zip

      - name: Update project on website
        run: |
          curl --fail -X POST -d repository=${{ github.repository }} -H "X-Update-Token: ${{ secrets.WEBSITE_UPDATE_TOKEN }}" https://selfcoders.com/update-project