on:
  workflow_call:
    inputs:
      php_versions:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ${{ fromJSON(inputs.php_versions) }}

    name: PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          coverage: xdebug

      - name: Get Composer cache path
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Execute PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text