on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update project on Packagist
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
